version: '3'
services: 
    redis-server:
        image: 'redis'
    node-app:
        build: ./visits
        ports:
            - "4001:8081"
    node-app-crash:
        build: ./visits _crash
        # restart: "no"
        restart: always
        # restart: on-failure
        # restart: unless-stopped
        ports:
            - "4002:8081"