version: '3'
services: 
    redis-server:
        image: 'redis'
    node-app:
        build: ./visits
        ports:
            - "4001:8081"
    node-app-crash:
        build: ./visits_crash
        ports:
            - "4002:8001"